# Generated by Django 4.1.1 on 2022-09-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_performance"),
    ]

    operations = [
        migrations.DeleteModel(name="Performance",),
    ]
