# Generated by Django 4.1.1 on 2022-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_performance_stock"),
    ]

    operations = [
        migrations.RemoveField(model_name="stock", name="id",),
        migrations.AlterField(
            model_name="stock",
            name="code",
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
